# Reading CSV

In [1]:
import pandas as pd

In [2]:
data = pd.read_csv("data.csv")

In [3]:
type(data)

pandas.DataFrame

In [5]:
data.head()

      name   surname     id_no   hours
0  michael    mutote    569969      13
1    naomi     feral   9888569      15
2     rosy   andrews  58222869      11

In [6]:
data.describe()

              id_no  hours
count  3.000000e+00    3.0
mean   2.289380e+07   13.0
std    3.094861e+07    2.0
min    5.699690e+05   11.0
25%    5.229269e+06   12.0
50%    9.888569e+06   13.0
75%    3.405572e+07   14.0
max    5.822287e+07   15.0

In [10]:
data[" surname"]

0      mutote
1       feral
2     andrews
Name:  surname, dtype: str

In [2]:
num = 9
type(num)

int